version: '3'

services:
  react-app:
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    command: npm run start
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: always